---
kind: pipeline
type: docker
name: lint-test

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: phoenix

steps:
- name: npm-install
  pull: always
  image: owncloudci/php
  commands:
  - yarn install

- name: lint-test
  pull: always
  image: owncloudci/php
  commands:
  - yarn run lint

trigger:
  ref:
  - refs/tags/**
  - refs/pull/**
  - refs/pull-requests/**
  - refs/merge-requests/**
  - refs/heads/master
  - refs/heads/release*
  - refs/heads/develop*

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  - refs/heads/release*
  - refs/heads/develop*

...
